name: Developer Fortune

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
  workflow_dispatch:

jobs:
  comment_fortune:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Generate Fortune
        id: GenerateFortune
        shell: /usr/bin/python {0}
        env:
          pythonLocation: /opt/hostedtoolcache/Python/3.11.3/x64
          LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.3/x64/lib
        run: | 
          import random

          fortunes = ["You will encounter a bug that will lead you down a rabbit hole of endless debugging. Keep calm and refactor on!",
                      "A breakthrough in your coding skills is just around the corner. Stay curious and embrace new technologies.",
                      "Your next project will challenge you, but it will also bring great satisfaction and recognition for your hard work.",
                      "A sudden burst of inspiration will lead you to create something truly innovative and groundbreaking. Trust your instincts.",
                      "A hidden gem in an open-source library will solve a problem you've been struggling with for days. Keep exploring and experimenting.",
                      "Collaboration will be key to your success. Seek out the expertise of your fellow developers and build something remarkable together.",
                      "An unexpected deadline extension will provide you with the time needed to refine your code and deliver an exceptional product.",
                      "Embrace the power of automation. Investing time in scripting and automating tasks will save you countless hours in the future.",
                      "A networking event or conference will lead to a fortuitous connection that opens doors to exciting new projects and opportunities."]
          
          quote = ranom.choice(fortunes)
          return(quote)
          
          
      - name: Comment on Issue or PR
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueOrPR = context.payload.issue || context.payload.pull_request;
            const fortune = "${{ steps.GenerateFortune.outputs.quote }}";
            const commentBody = `**Fortune:** ${fortune}`;
            const issueComment = await github.issues.createComment({
              ...context.repo,
              issue_number: issueOrPR.number,
              body: commentBody
            });
            console.log(`Commented on ${issueOrPR.html_url}`);
